language: scala
dist: trusty
sudo: false

jdk:
- oraclejdk8
- openjdk9
- openjdk10
- openjdk11
- openjdk-ea

scala:
- 2.11.12
- 2.12.7

script: sbt ++$TRAVIS_SCALA_VERSION clean scalastyle test:scalastyle coverage test coverageReport
after_success: bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
  - "$HOME/.embedpostgresql"
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
- find $HOME/.sbt -name "*.lock" -delete
env:
  global:
    - DEFAULT_TIMEOUT_MILLIS=300 #Reactive Streams testkit timeout for async ops
  matrix:
  - PG_VER=V9_6
  - PG_VER=V10